server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: habit-service
              uri: http://localhost:8081
              predicates:
                - Path=/habits/**
            - id: tracker-service
              uri: http://localhost:8082
              predicates:
                - Path=/tracker/**
            - id: user-service
              uri: http://localhost:8083
              predicates:
                - Path=/user/**


  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
