server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: habit-service
          uri: http://localhost:8081
          predicates:
            - Path=/habits/**
        - id: tracker-service
          uri: http://localhost:8082
          predicates:
            - Path=/tracker/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

