spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db
      database: user_db

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
