spring:
  application:
    name: habit-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/habit_db

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

